from termcolor import colored

print colored ("harriet","blue")
print colored ("i am a good girlls","green")
print colored ("*****************","red")
print colored ("*****************","red")
print colored ("*****************","red")
print colored ("*****************","yellow")
print colored ("*****************","yellow")
print colored ("*****************","yellow")
print colored ("*****************","green")
print colored ("*****************","green")
print colored ("*****************","green")
print colored ("*****************","red")
print colored ("*****************","red")
print colored ("*****************","red")
print colored ("*****************","red")
print colored ("this is red","red")
print colored ("this is yellow","yellow")
print colored ("this is green","green")
print colored ("this is blue","blue")