print "hello world"
print "mary melissa"
print "apple,orange,grape,guava,strawberry,banana,mango,pear,blueberry,blackberry"
print "apple"
print "orange"
print "guava"
print "grape"
print "strawberry"
print "banana"
print "mango"
print "pear"