print "hello world"
print "special"
print "celestina"
print "mango"
print "apple"
print "pineapple"
print "raspberry"
print "strawberry"
print "orange"
print "banana"
print "cherry"
print "peach"
print "watermelon"