print "banku with shito"
print "rice and stew"
print "jollof rice"
print "fufu with soup"
print "yam with stew"
print "fried rice and chicken"
print "kenkey and fish"
print "porridge with bread"
print "omotuo with groundnut"
print "face the wall with okro soup"
