from termcolor import colored
print colored ("GHANAIAN MEALS:", "red")
print "***************"
print "1. Fufu"
print "2. Tuo"
print "3. Banku"
print "4. Etsiw"
print "5. Akpele"
print "6. Aprapransa"
print "7. Ayoyo"
print "8. Kenkey"
print "9. Mpotonmpoto"
print "10. Eto"
print "11. Waakye"
print "12. Konkonte"
print "13. Apregyie"
