print "hello world"
print "Lilian Oppong Pomah"
print"syivia tagoe"
print "mango"
print"banana"
print"orange"
print"pineapple"
print"grape"
print"pawpaw"
print"water melon"
print"coconuts"
print"stawberry"
print"blackberry"